"""update BoardGame for game_id

Revision ID: aeaa3f23ca01
Revises: ef16d39ae98e
Create Date: 2020-10-13 11:07:38.368136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeaa3f23ca01'
down_revision = 'ef16d39ae98e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boardgames', sa.Column('game_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boardgames', 'game_id')
    # ### end Alembic commands ###
