"""updated models with BoardGames and GameCondition

Revision ID: c8323776e63f
Revises: 867691bbd971
Create Date: 2020-10-07 13:44:55.903596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8323776e63f'
down_revision = '867691bbd971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boardgames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('year_published', sa.Integer(), nullable=True),
    sa.Column('thumb_url', sa.String(length=300), nullable=True),
    sa.Column('msrp', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('forsale', sa.Boolean(), nullable=False),
    sa.Column('fortrade', sa.Boolean(), nullable=False),
    sa.Column('forborrow', sa.Boolean(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['gamecondition.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamecondition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('previous_condition', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['boardgames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_collection',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['boardgames.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'game_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_collection')
    op.drop_table('gamecondition')
    op.drop_table('boardgames')
    # ### end Alembic commands ###
