"""adding offers

Revision ID: e3da901894e9
Revises: 65ff1aae6851
Create Date: 2020-10-30 00:40:08.857167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3da901894e9'
down_revision = '65ff1aae6851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('offeree_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('new_offer', sa.Boolean(), nullable=False),
    sa.Column('pending_offer', sa.Boolean(), nullable=False),
    sa.Column('offer_buy', sa.Boolean(), nullable=False),
    sa.Column('offer_trade', sa.Boolean(), nullable=False),
    sa.Column('offer_borrow', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['boardgames.id'], ),
    sa.ForeignKeyConstraint(['offeree_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('boardgames', sa.Column('borrowed', sa.Boolean(), nullable=False))
    op.add_column('boardgames', sa.Column('borrower_id', sa.Integer(), nullable=True))
    op.add_column('boardgames', sa.Column('pending_borrow_offer', sa.Boolean(), nullable=False))
    op.add_column('boardgames', sa.Column('pending_buy_offer', sa.Boolean(), nullable=False))
    op.add_column('boardgames', sa.Column('pending_trade_offer', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'boardgames', 'users', ['borrower_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'boardgames', type_='foreignkey')
    op.drop_column('boardgames', 'pending_trade_offer')
    op.drop_column('boardgames', 'pending_buy_offer')
    op.drop_column('boardgames', 'pending_borrow_offer')
    op.drop_column('boardgames', 'borrower_id')
    op.drop_column('boardgames', 'borrowed')
    op.drop_table('offers')
    # ### end Alembic commands ###
