"""updating BoardGame for selling

Revision ID: ef16d39ae98e
Revises: 9948db02261c
Create Date: 2020-10-12 12:12:29.267745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef16d39ae98e'
down_revision = '9948db02261c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boardgames', sa.Column('condition_description', sa.String(length=200), nullable=True))
    op.add_column('boardgames', sa.Column('sale_price', sa.Integer(), nullable=True))
    op.alter_column('boardgames', 'condition',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boardgames', 'condition',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_column('boardgames', 'sale_price')
    op.drop_column('boardgames', 'condition_description')
    # ### end Alembic commands ###
